name: Build LaTeX Notes

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get changed note directories
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          files: theNotesHERE/**

      - name: Build and rename PDFs
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          echo "Changed note directories:"
          CHANGED_DIRS=$(echo "${{ steps.changed-files.outputs.all_changed_files }}" | xargs -n1 dirname | sort -u)
          echo "$CHANGED_DIRS"
          
          for dir in $CHANGED_DIRS; do
            if [ -f "$dir/main.tex" ]; then
              echo "Building PDF for $dir"
              # Compile the LaTeX file
              docker run --rm -v "$(pwd)":/workdir -w /workdir ghcr.io/xu-cheng/texlive-full:latest latexmk -pdf -cd -interaction=nonstopmode -outdir="$dir" "$dir/main.tex"

              # Rename the output PDF
              FOLDER_NAME=$(basename "$dir")
              PDF_NAME="_${FOLDER_NAME}-PDF.pdf"
              mv "$dir/main.pdf" "$dir/$PDF_NAME"
              echo "Renamed PDF to $PDF_NAME"
            else
              echo "No main.tex found in $dir, skipping."
            fi
          done

      - name: Upload PDFs
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: LaTeX-PDFs
          path: |
            theNotesHERE/*/*.pdf
            !theNotesHERE/*/*.tex