name: Build LaTeX Notes

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get changed note directories
        id: changed-dirs
        uses: tj-actions/changed-files@v41
        with:
          files: theNotesHERE/**

      - name: Build LaTeX and Rename PDFs
        id: build-latex
        if: steps.changed-dirs.outputs.any_changed == 'true'
        # Continue even if a build fails, so we can upload logs
        continue-on-error: true
        run: |
          # This variable will track if any LaTeX build fails.
          HAD_ERROR=false
          
          # Get a unique list of directories that have changed files.
          CHANGED_DIRS=$(echo "${{ steps.changed-dirs.outputs.all_changed_files }}" | xargs -n1 dirname | sort -u)
          
          echo "Found changes in the following directories:"
          echo "$CHANGED_DIRS"

          for dir in $CHANGED_DIRS; do
            if [ -f "$dir/main.tex" ]; then
              echo "--- Building PDF for $dir ---"
              
              # Run the compilation. If it fails, print an error and set the flag.
              if ! docker run --rm -v "$(pwd)":/workdir -w /workdir ghcr.io/xu-cheng/texlive-full:latest latexmk -pdf -cd -interaction=nonstopmode "$dir/main.tex"; then
                echo "::error::LaTeX compilation failed for $dir. Check the log files."
                HAD_ERROR=true
              else
                # On success, rename the PDF
                FOLDER_NAME=$(basename "$dir")
                PDF_NAME="_${FOLDER_NAME}-PDF.pdf"
                mv "$dir/main.pdf" "$dir/$PDF_NAME"
                echo "Successfully built and renamed $dir/$PDF_NAME"
              fi
            fi
          done

          # If any build failed, exit with an error code to mark this step as failed.
          if [ "$HAD_ERROR" = true ]; then
            exit 1
          fi

      - name: Upload PDF Artifacts on Success
        if: steps.build-latex.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: LaTeX-PDFs
          path: |
            theNotesHERE/*/*.pdf
            !theNotesHERE/*/*.tex

      - name: Upload Log Artifacts on Failure
        # This step runs only if the build step failed.
        if: steps.build-latex.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: LaTeX-Logs-(check-for-errors)
          path: |
            theNotesHERE/*/*.log