name: Build and Commit LaTeX PDFs

on:
  push:
    branches:
      - main

# --- THIS IS THE FINAL FIX ---
# Grant the GITHUB_TOKEN permissions to write to the repository
permissions:
  contents: write

jobs:
  build:
    if: ${{ !contains(github.event.head_commit.message || '', 'ci: Automatically build and commit PDFs') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get changed note directories
        id: changed-dirs
        uses: tj-actions/changed-files@v41
        with:
          files: theNotesHERE/**

      - name: Build LaTeX and Rename PDFs
        id: build-latex
        if: steps.changed-dirs.outputs.any_changed == 'true'
        continue-on-error: true
        run: |
          HAD_ERROR=false
          CHANGED_DIRS=$(echo "${{ steps.changed-dirs.outputs.all_changed_files }}" | xargs -n1 dirname | sort -u)
          echo "Found changes in the following directories:"
          echo "$CHANGED_DIRS"
          for dir in $CHANGED_DIRS; do
            if [ -f "$dir/main.tex" ];
            then
              echo "--- Building PDF for $dir ---"
              if ! docker run --rm --user $(id -u):$(id -g) -v "$(pwd)":/workdir -w /workdir ghcr.io/xu-cheng/texlive-full:latest latexmk -pdf -cd -interaction=nonstopmode "$dir/main.tex"; then
                echo "::error::LaTeX compilation failed for $dir. Check the log files."
                HAD_ERROR=true
              else
                FOLDER_NAME=$(basename "$dir")
                PDF_NAME="_${FOLDER_NAME}-PDF.pdf"
                mv "$dir/main.pdf" "$dir/$PDF_NAME"
                echo "Successfully built and renamed $dir/$PDF_NAME"
              fi
            fi
          done
          if [ "$HAD_ERROR" = true ]; then
            exit 1
          fi

      - name: Forcefully add PDF files to git
        if: steps.build-latex.outcome == 'success'
        run: git add -f theNotesHERE/**/*.pdf

      - name: Commit PDF files
        if: steps.build-latex.outcome == 'success'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "ci: Automatically build and commit PDFs"
          commit_user_name: GitHub Actions Bot
          commit_user_email: actions@github.com

      - name: Upload Log Artifacts on Failure
        if: steps.build-latex.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: LaTeX-Logs-(check-for-errors)
          path: |
            theNotesHERE/*/*.log