name: Build LaTeX Notes

on:
  # manual trigger button in the Actions tab
  workflow_dispatch:

  # automatic run on every push to main that touches .tex files
  push:
    branches: [ main ]
    paths:
      - "**/*.tex"
      - ".github/workflows/**"

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      # Pull your repo
      - name: Checkout repo
        uses: actions/checkout@v3

      # Tiny TeX Live distribution + latexmk
      - name: Set up TeX Live
        uses: xu-cheng/latex-action@v2

      # Compile all main.tex files (recursively)
      - name: Compile every main.tex
        shell: bash
        run: |
          set -eu
          mapfile -t TEX_FILES < <(git ls-files '**/main.tex')
          echo "Found ${#TEX_FILES[@]} note folders."
          for TEX in "${TEX_FILES[@]}"; do
            DIR=$(dirname "$TEX")
            FOLDER=$(basename "$DIR")
            echo "▶︎ Building $TEX  →  _${FOLDER}-PDF.pdf"
            latexmk -pdf -interaction=nonstopmode -halt-on-error \
                    -jobname="_${FOLDER}-PDF" "$TEX"
          done

      # Collect all generated PDFs
      - name: Upload PDFs
        uses: actions/upload-artifact@v4
        with:
          name: compiled-notes
          path: "**/_*-PDF.pdf"
